
#?????80??
server:
  port: 80

#????????????
spring:
  application:
    name: SpringCloud_User

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/