
server:
    port: 8881
#??????????
spring:
    datasource:
        name: product_customer_management
        url: jdbc:mysql://localhost:3306/product_customer_management?serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: springcloudprovider
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.springcloud_provider.bean
    config-location: classpath:mybatis-config.xml

eureka:
    instance:
        prefer-ip-address: true

        hostname: localhost
    client:
        register-with-eureka: true
        fetch-registry: false
        service-url:
            defaultZone: http://localhost:8761/eureka/